---
title: "Comparison between different colormaps for element mapping"
author: "Max Hohl"
date: "22/10/2021"
output:
  bookdown::html_document2:
    toc: yes
    toc_float: no
    df_print: paged
    fig.cation: yes
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


```{r}
library(tidyverse)
#library(cowplot)
```

Install required packages for the this project. `colorspace` and `colorblindr`
simulate the colormaps the way colorblind people see them. The `geochem` package
includes plotting functions for element maps.

```{r}
# install.packages("colorspace", repos = "http://R-Forge.R-project.org")
# remotes::install_github("clauswilke/colorblindr")
# remotes::install_github("muhohl/geochem")
```

# Comparison of Colormaps

## Rainbow 

```{r}
rainbow_palette <- rev(c("#CCCCCC", "#8B0000", "#FF0000", "#FFA500",
                     "#FFFF00", "#00FF00", "#90EE90",
                     "#ADD8E6", "#00008B",  "#A020F0", "#000000"))
colorblindcheck::palette_check(rainbow_palette, plot = TRUE, )
```


```{r}
heat_palette <- rev(c("#FFFF00", "#FFA500", "#FF0000", "#8B0000", "#000000"))
colorblindcheck::palette_check(heat_palette, plot = TRUE)
```

```{r}
colorblindcheck::palette_check(viridis::viridis(11), plot = TRUE)
```


# Element Maps

```{r}
df_element_map <- read_csv("Image_data.csv")
```

```{r}
i <- 1
rainbow_element_maps <- list()
for (element in names(df_element_map[-c(1:2)])) {
    p.rainbow <- ggplot(data = df_element_map,
                aes(x, y,
                    fill = !!sym(element))) +
    geom_raster(interpolate = TRUE) +
    coord_fixed(ratio = 1) +
    scale_y_discrete(expand = c(0,0)) +
    scale_x_discrete(expand = c(0,0)) +
    labs(fill = "",
         y = "",
         x = "") +
    ggtitle(paste(element, "ppm")) +
    scale_fill_gradientn(colors = rainbow_palette,
                         trans = "log",
                         breaks = c(1, 10, 100, 1000, 10000),
                         labels = scales::label_scientific()) +
    theme_bw() +
    theme(panel.border = element_blank(),
          text = element_text(family = "serif",
                              size = 16)) +
    guides(fill = guide_colorbar(barwidth = unit(1, "lines"),
                                 barheight = unit(8, "lines"),
                                 ticks.colour = "black", 
                                 frame.colour = "black"))
    rainbow_element_maps[[i]] <- p.rainbow
    i <- i+1
}
p.g.rainbow <- cowplot::plot_grid(plotlist = rainbow_element_maps)

```

```{r, fig.width=12, fig.height=7}
p.g.rainbow
```

```{r}
i <- 1
heat_element_maps <- list()
for (element in names(df_element_map[-c(1:2)])) {
    p.rainbow <- ggplot(data = df_element_map,
                aes(x, y,
                    fill = !!sym(element))) +
    geom_raster(interpolate = TRUE) +
    coord_fixed(ratio = 1) +
    scale_y_discrete(expand = c(0,0)) +
    scale_x_discrete(expand = c(0,0)) +
    labs(fill = "",
         y = "",
         x = "") +
    ggtitle(paste(element, "ppm")) +
    scale_fill_gradientn(colors=heat_palette,
                         trans = "log",
                         breaks = c(1, 10, 100, 1000, 10000),
                         labels = scales::label_scientific()) +
    theme_bw() +
    theme(panel.border = element_blank(),
          text = element_text(family = "serif",
                              size = 16)) +
    guides(fill = guide_colorbar(barwidth = unit(1, "lines"),
                                 barheight = unit(8, "lines"),
                                 ticks.colour = "black", 
                                 frame.colour = "black"))
    heat_element_maps[[i]] <- p.rainbow
    i <- i+1
}
p.g.heat <- cowplot::plot_grid(plotlist = heat_element_maps)
```

```{r, fig.width=12, fig.height=7}
p.g.heat
```

```{r}
viridis_d_element_maps <- 
    geochem::laser_map(data = df_element_map, 
                       selected_elements = names(df_element_map[-c(1:2)]))
cowplot::plot_grid(plotlist = viridis_d_element_maps)
```

```{r}
viridis_b_element_maps <- 
    geochem::laser_map(data = df_element_map, 
                       selected_elements = names(df_element_map[-c(1:2)]),
                       option = "B")
cowplot::plot_grid(plotlist = viridis_b_element_maps)
```

```{r, fig.height=8, fig.width=10}
cowplot::plot_grid(rainbow_element_maps[[4]],
                   colorblindr::cvd_grid(plot = rainbow_element_maps[[4]]),
                   nrow = 2, rel_heights = c(0.33, 0.67))
```

```{r, fig.height=8, fig.width=10}
cowplot::plot_grid(heat_element_maps[[4]],
                   colorblindr::cvd_grid(plot = heat_element_maps[[4]]),
                   nrow = 2, rel_heights = c(0.33, 0.67))

```

```{r, fig.height=8, fig.width=10}
cowplot::plot_grid(viridis_b_element_maps[[4]],
                   colorblindr::cvd_grid(plot = viridis_b_element_maps[[4]]),
                   nrow = 2, rel_heights = c(0.33, 0.67)
)
```

```{r, fig.height=8, fig.width=10}
cowplot::plot_grid(viridis_d_element_maps[[4]],
                   colorblindr::cvd_grid(plot = viridis_d_element_maps[[4]]),
                   nrow = 2, rel_heights = c(0.33, 0.66)
                   )
```

```{r, fig.height=8, fig.width=10}
cowplot::plot_grid(rainbow_element_maps[[5]],
                   colorblindr::cvd_grid(plot = rainbow_element_maps[[5]]),
                   nrow = 2, rel_heights = c(0.33, 0.67))
```


```{r, fig.height=8, fig.width=10}
cowplot::plot_grid(viridis_d_element_maps[[5]],
                   colorblindr::cvd_grid(plot = viridis_d_element_maps[[5]]),
                   nrow = 2, rel_heights = c(0.33, 0.66)
                   )
```

# Session Info

```{r}
sessionInfo()
```

